# Generated by Django 3.2.5 on 2021-08-07 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_phone', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10, null=True)),
                ('p_age', models.IntegerField(null=True)),
                ('p_place', models.CharField(max_length=100)),
                ('problem', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(default='sunrise hospital', max_length=100)),
                ('location', models.CharField(default='Banglore', max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.patient')),
            ],
        ),
    ]
