# Generated by Django 3.2.5 on 2021-08-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('place', models.CharField(default='Andhra', max_length=200)),
                ('review', models.CharField(blank=True, max_length=200, null=True)),
                ('present', models.BooleanField(null=True)),
            ],
        ),
    ]
