# Generated by Django 3.2.5 on 2021-08-03 04:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210803_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='student_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.TextField(blank=True, help_text='pls fill rating staring from 5', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='student_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 4, 39, 30, 753743, tzinfo=utc)),
        ),
    ]
