# Generated by Django 3.2.5 on 2021-08-03 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210803_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(default='sravs@gamil.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='book',
            name='student_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 6, 10, 20, 245720, tzinfo=utc)),
        ),
    ]
