# Generated by Django 3.2.5 on 2021-08-11 05:49

import app1.models
import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_book_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, validators=[app1.models.validate_delhi]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='book',
            name='resume',
            field=models.FileField(null=True, upload_to='userfiles/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='book',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[app1.models.validate_com]),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='student_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 5, 48, 27, 713223, tzinfo=utc)),
        ),
    ]
